# Test the documentation on SSH hardening
task:
  matrix:
    - name: 12.4-RELEASE
      freebsd_instance:
        image_family: freebsd-12-4
    - name: 12.4-STABLE
      freebsd_instance:
        image_family: freebsd-12-4-snap
    - name: 13.2-RELEASE
      freebsd_instance:
        image_family: freebsd-13-2
    - name: 13.2-STABLE
      freebsd_instance:
        image_family: freebsd-13-2-snap
    - name: 14.0-CURRENT
      freebsd_instance:
        image_family: freebsd-14-0-snap
  use_latest_packages_script:
    - mkdir -p /usr/local/etc/pkg/repos
    - cp .cirrus/FreeBSD.conf /usr/local/etc/pkg/repos/
  ssh-hardening_script:
    - sed -i '' 's/^/#/' README.md
    - sed -i '' '/^#         .*$/d' README.md
    - sed -i '' 's/^#    //' README.md
    - printf "#\!/bin/sh\n%s\n" "$(cat README.md)" > ssh-hardening.sh
    - sh ./ssh-hardening.sh
    - sh .cirrus/check_for_recommendations.sh

  always:
    ssh-audit.out_artifacts:
      path: ssh-audit.out
      type: text/plain
