# Test the documentation on SSH hardening
task:
  matrix:
    - name: 12.2-RELEASE
      freebsd_instance:
        image_family: freebsd-12-2
    - name: 12.2-STABLE
      freebsd_instance:
        image_family: freebsd-12-2-snap
    - name: 13.0-RELEASE
      freebsd_instance:
        image_family: freebsd-13-0
    - name: 13.0-STABLE
      freebsd_instance:
        image_family: freebsd-13-0-snap
    - name: 14.0-CURRENT
      freebsd_instance:
        image_family: freebsd-14-0-snap
  ssh-hardening_script:
    - sed -i '' 's/^/#/' README.md
    - sed -i '' '/^#         .*$/d' README.md
    - sed -i '' 's/^#    //' README.md
    - printf "#\!/bin/sh\nset -e\n%s\n" "$(cat README.md)" > ssh-hardening.sh
    - sh ./ssh-hardening.sh
  always:
    ssh-audit.out_artifacts:
      path: ssh-audit.out
      type: text/plain
